// Generated by CoffeeScript 1.9.0
(function() {
  var socket;

  socket = io();

  window.onload = function() {
    var name;
    name = window.prompt("What is your name?", "Guest");
    return socket.emit("join", [name]);
  };

  socket.on("join", function(names) {
    return names.forEach(function(name) {
      var li;
      console.log(name + " joined");
      li = document.createElement("LI");
      li.innerHTML = name;
      return document.getElementById("people").appendChild(li);
    });
  });

}).call(this);
